FROM mysql:5.6
MAINTAINER ram "ramakoteswara.venkateswarlu@softsuave.com"
RUN apt-get update && apt-get install -y wget
RUN apt-get install mysql-server -y
RUN mkdir -p /backup/xtrabackups
#RUN /bin/bash -c "/usr/bin/mysqld_safe --skip-grant-tables &"
RUN mysql -u root -e "CREATE DATABASE mydb"
RUN mysql -u root -p password mydb < test-dump.sql
#ADD test-dump.sql /backup/xtrabackups/
EXPOSE 2020
